### ISSUE TITLE
panic on load-image

### ISSUE THREAD

**Issue by incanus** [technoblogy/ulisp-tdeck#4]
With release 4 (28e546a6dc63bc6083ada7fe8b1ff1b5b971fc22) I'm getting a panic when running `(load-image)` for my relatively small (1-2 functions) image. 

```
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x42096247  PS      : 0x00060a30  A0      : 0x8209625c  A1      : 0x3fcebce0  
A2      : 0xb4f67002  A3      : 0x00000001  A4      : 0x00000000  A5      : 0x3fcf06b4  
A6      : 0x00008000  A7      : 0x0000000a  A8      : 0x82010eac  A9      : 0x3fcebca0  
A10     : 0x3fcecc88  A11     : 0x3fcebcc0  A12     : 0x00000884  A13     : 0x00000000  
A14     : 0x00000001  A15     : 0x3fced260  SAR     : 0x0000001f  EXCCAUSE: 0x0000001c  
EXCVADDR: 0xb4f67002  LBEG    : 0x400570a4  LEND    : 0x400570a9  LCOUNT  : 0x00000000  


ELF file SHA256: b45ff5356f9d12d7

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x42098216
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a68
entry 0x403c98d4
```

I can possibly spend some time tracking this down, but here's the associated binaries for now. 

[ulisp-tdeck.ino.zip](https://github.com/technoblogy/ulisp-tdeck/files/13173259/ulisp-tdeck.ino.zip)

**Comment by technoblogy** [comment]
I assume you've previously saved an image?

Are you saving the image to flash memory or SD card? In other words, do you have:

    #define sdcardsupport

uncommented?

**Comment by incanus** [comment]
Yes, a saved image was previously loading on release 3. I am using the SD card.

**Comment by technoblogy** [comment]
Ah, sorry, images aren't guaranteed to be compatible across releases. If there's something valuable there reload it with a copy of Release 3 and print it with **pprintall**.

**Comment by technoblogy** [comment]
I thought this was documented in the description of **save-image**, but I've just checked and found that it wasn't. Apologies - I'll add that.

**Comment by incanus** [comment]
I see it [there](http://www.ulisp.com/show?3L#saveimage) now, thanks.
