### ISSUE TITLE
Can reinstall ulisp

### ISSUE THREAD

**Issue by marto68** [technoblogy/ulisp-tdeck#6]
I initially installed ulisp v5 following the documented instructions and it worked fine.
Today I tried to install the edit program, also following the instructions and I got a black screen.
To check the device, I installed the T-deck Factory firmware .bin and that worked , so 
I flashed ulisp again without the editor.
Now all I get is a black screen.
I can actually connect to it via the serial monitor, so I don't know what I've done wrong.

I'm not sure what to do, has anyone got some ideas?
It would be much appreciated.

**Comment by technoblogy** [comment]
Have you tried typing and pressing Return?

**Comment by marto68** [comment]
Hi, thanks for the quick reply. I was just about to delete my issue. 

Downloaded all source files again, and also deleted the TFT_eSPI  library 
and used the one I downloaded last week.
There was an update for that library that I applied.
After doing that it now works!
Thanks for all your work

**Comment by technoblogy** [comment]
Yes, you have to use the TFT_eSPI from the LilyGO T-Deck repository, because they've modified it to work with the T-Deck.

Glad you got it working!
