### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by vrz** [technoblogy/ulisp-tdeck#7]
Do you plan to renew version uLisp for T-Deck board?
ulisp-esp currently has version 4.6b, but version uLisp for T-Deck stay 4.4e.

**Comment by technoblogy** [comment]
Yes, I can do that.

**Comment by vrz** [comment]
It would be great, if you wil do it.

**Comment by technoblogy** [comment]
Hi Vladimir, I've got a beta version of the latest ESP uLisp ported to the T-Deck, but there's one issue I'd like to solve before releasing it.

It works fine, like Release 5, with 22000 cells of RAM workspace, with or without the SD card interface enabled.

It also allows you to use the 8MB PSRAM, to get 1000000 cells of workspace, but this prevents the SD card interface from working. Attempting to use the SD card gives an error:

    assert failed: remove_free_block heap_tlsf.c:206 (next && "next_free field can not be null")

Do you have any ideas about what could be causing this?

I'd be happy to give you this version to try out, with this reservation.

**Comment by technoblogy** [comment]
I've solved that problem, and uploaded a Release 5 which is updated to ESP uLisp Release 4.6c, including support for the PSRAM on the T-Deck to give a workspace of 1000000 cells!

**Comment by vrz** [comment]
Great, thanx!
Which option is better to set for PSRAM: QSPI or OPI?

**Comment by technoblogy** [comment]
The only one that worked for me was "OPI PSRAM".

I've documented it here: [LilyGO T-Deck uLisp Machine - Installation](http://www.ulisp.com/show?4JAO#installation)

**Comment by vrz** [comment]
thanx
