### ISSUE TITLE
webpage wi-fi example throws 'too many arguments' error

### ISSUE THREAD

**Issue by 3ahptk** [technoblogy/ulisp-tdeck#9]
**Reproduction Steps**

1. Flash latest (release 6) on T-Deck
2. Use `wifi-connect` to connect to local wifi
3. Type in and run the `webpage` example in the [Wi-Fi examples](http://www.ulisp.com/show?2B22)

Current: throws "too many arguments" error
Expected: should return rss entry from `http://www.ulisp.com/rss?1DQ5`

Work around: revert to Release 5

**Comment by technoblogy** [comment]
Thanks - I can't see anything obviously different between Release 5 and Release 6.
Could you give the whole line of the error message?
Otherwise I'll try it out myself.
David

**Comment by 3ahptk** [comment]
All I get back is `Error: 'with-client' too many arguments`

I also tried loading the example from an SD card just in case I fat fingered it, but I still get the same error.

**Comment by technoblogy** [comment]
OK, it's `with-client` that's causing the error. I'll investigate.
David

**Comment by technoblogy** [comment]
OK, I've found the problem. In the Release 6 source change the line:

      { string212, sp_withclient, 0313, doc212 },

to:

      { string212, sp_withclient, 0317, doc212 },

Sorry for that, and thank you for finding it. I'll post an updated version.

David
